require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'change']

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/environments/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 150
  AllowedPatterns: ['\A#', '\ARSpec']
  Exclude:
    - Gemfile

RSpec/AnyInstance:
  Exclude:
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/SymbolConversion:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# This cops ensures a class structure is followed
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/ClassStructure
Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/BooleanSymbol:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
