version: '3'
services:
  db:
    image: amd64/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5003 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/rent_a_book
    ports:
      - "5003:5003"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  postgres_data:
networks:
  default:
    external:
      name: rent_a_book
